main/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
	path('', views.store, name='store'),
	path('products/', views.products, name='products'),
	path('services/', views.services, name='services'),
	path('gallery/', views.gallery, name='gallery'),
	path('price/', views.price, name='price'),
	path('contacts/', views.contacts, name='contacts'),
	path('<int:product_id>/', views.detail, name='detail'),
	path('s<int:sproduct_id>/', views.sdetail, name='sdetail'),
	path('<slug:url>/', views.product_category, name='product_category'),
	path('s/<slug:surl>/', views.sproduct_category, name='sproduct_category')
]

store/models.py
from django.db import models


class Category(models.Model):
	name = models.CharField('Название', max_length=50)
	url = models.SlugField('URL', max_length=200, unique=True, default='')
	image = models.ImageField('Фото', null=True, blank=True)
	description = models.TextField('Описание', default='')
	objects = models.Manager()

	class Meta:
		verbose_name = 'Категория'
		verbose_name_plural = 'Категории'

	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''

		return url

class Product(models.Model):
	category = models.ForeignKey(Category, verbose_name='Катерогия товаров', on_delete=models.SET_NULL, null=True)
	name = models.CharField('Название', max_length=200)
	price = models.FloatField('Цена')
	availability = models.BooleanField('В наличии', default=False,null=True, blank=True)
	image = models.ImageField('Фото', null=True, blank=True)
	description = models.TextField('Описание', default='')
	contact = models.TextField('Контакты', default='')
	objects = models.Manager()

	class Meta:
		verbose_name = 'Товар'
		verbose_name_plural = 'Товары'

	def __str__(self):
		return self.name

	def is_availible(self):
		return self.availability

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''

		return url

class Pricelist(models.Model):
	name = models.CharField('Название', max_length=200)
	price = models.FloatField('Цена')
	objects = models.Manager()

	class Meta:
		verbose_name = 'Прайс-лист'
		verbose_name_plural = 'Прайс-листы'

	def __str__(self):
		return self.name

class Gallery(models.Model):
	name = models.CharField('Название', max_length=200, default='Фото')
	image = models.ImageField('Фото', null=True, blank=True)
	objects = models.Manager()

	class Meta:
		verbose_name = 'Галерея'
		verbose_name_plural = 'Галереи'

	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''

		return url

class SCategory(models.Model):
	name = models.CharField('Название категории', max_length=50)
	url = models.SlugField('URL', max_length=200, unique=True, default='')
	image = models.ImageField('Фото', null=True, blank=True)
	description = models.TextField('Описание', default='')
	objects = models.Manager()

	class Meta:
		verbose_name = 'Категория услуг'
		verbose_name_plural = 'Категории услуг'

	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''

		return url

class SProduct(models.Model):
	category = models.ForeignKey(SCategory, verbose_name='Катерогия услуг', on_delete=models.SET_NULL, null=True)
	name = models.CharField('Название услуги', max_length=200)
	price = models.FloatField('Цена')
	image = models.ImageField('Фото', null=True, blank=True)
	description = models.TextField('Описание', default='')
	contact = models.TextField('Контакты', default='')
	objects = models.Manager()

	class Meta:
		verbose_name = 'Услуга'
		verbose_name_plural = 'Услуги'

	def __str__(self):
		return self.name

	def is_availible(self):
		return self.availability

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''

		return url

store/views.py
import json
import datetime
from django.http import JsonResponse
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import Category, Product, Pricelist, Gallery, SCategory, SProduct

def store(request):
	menu = Category.objects.all()

	context = {
		'menu': menu
		}

	return render(request, 'store/store.html', context)

def product_category(request, url):
	menu = Category.objects.all()

	products_list = Product.objects.filter(category__url=url).order_by('name')

	try:
		category_name = products_list[0].category.name
	except:
		category_name = 'Товары не найдены'

	products_count = products_list.count()

	context = {
		'object_list': products_list,
		'category': category_name,
		'count': products_count,
		'menu': menu
	}

	return render(request, 'store/product_category.html', context)

def detail(request, product_id):
	menu = Category.objects.all()

	try:
		product = Product.objects.get(id=product_id)
	except:
		raise Http404('Товар с указанным ID не найден.')

	context = {
		'product': product,
		'menu': menu
	}

	return render(request, 'store/detail.html', context)

def products(request):
	menu = Category.objects.all()

	context = {
		'menu': menu
	}

	return render(request, 'store/products.html', context)

def price(request):
	price = Pricelist.objects.all()

	context = {
		'price': price
	}

	return render(request, 'store/price.html', context)

def contacts(request):
	return render(request, 'store/contacts.html')

def services(request):
	menu = SCategory.objects.all()

	context = {
		'menu': menu
	}

	return render(request, 'store/services.html', context)

def gallery(request):
	gallery = Gallery.objects.all()

	context = {
		'gallery': gallery
	}

	return render(request, 'store/gallery.html', context)

def sproduct_category(request, surl):
	menu = SCategory.objects.all()

	products_list = SProduct.objects.filter(category__url=surl).order_by('name')

	try:
		category_name = products_list[0].category.name
	except:
		category_name = 'Услуги не найдены'

	products_count = products_list.count()

	context = {
		'object_list': products_list,
		'category': category_name,
		'count': products_count,
		'menu': menu
	}

	return render(request, 'store/sproduct_category.html', context)

def sdetail(request, sproduct_id):
	menu = SCategory.objects.all()

	try:
		product = SProduct.objects.get(id=sproduct_id)
	except:
		raise Http404('Услуга с указанным ID не найден.')

	context = {
		'product': product,
		'menu': menu
	}

	return render(request, 'store/sdetail.html', context)

store/templates/store/contacts.html
{% extends 'store/main.html' %}
{% load static %}
{% block title %}Контакты{% endblock %}
{% block content %}
<div id="content">
    <div class="inner clearfix">
        <div id="workarea" class="full clearfix">
            <div id="breadcrumbs" class="default"> <span>
                    <a href="{% url 'store:store' %}" title="Главная">Главная</a>
                </span> <span>>
                    Контакты </span> </div>
            <h1 class="title">Контакты</h1>
            <div class="clearfix">
                <div class="col-left">
                    <h4> Питомник растений Вита Плант </h4>
                    <p> <b>Адрес</b>
                        <br> г. Саратов, Вольский тракт, 4б </p>
                    <p> <b>Телефоны</b>
                        <br> (8452)40-01-51
                        <br> 8-903-384-49-84 </p>
                    <p> <b>E-mail</b>
                        <br> <a href="vitaplantsar@mail.ru">vitaplantsar@mail.ru</a> </p>
                    <p> <b>Время работы:</b>
                        <br> C апреля по ноябрь ежедневно с 9.00 до 18.00 </p>
                </div>
                <div class="col-right">
                    <div class="bx-yandex-view-layout">
                        <div class="bx-yandex-view-map">
                            <div id="map" style="width: 600px; height: 400px"></div>
                            <script type="text/javascript">
                            ymaps.ready(init);

                            function init() {
                                var myMap = new ymaps.Map("map", {
                                    center: [51.632122, 45.982523],
                                    zoom: 12,
                                    controls: [

                                        'zoomControl',
                                        'rulerControl',
                                        'routeButtonControl',
                                        'trafficControl',
                                        'typeSelector',
                                        'fullscreenControl',

                                        new ymaps.control.SearchControl({
                                            options: {
                                                size: 'large',
                                                provider: 'yandex#search'
                                            }
                                        })

                                    ]
                                });

                                var myPlacemark = new ymaps.Placemark([51.632122, 45.982523], {
                                    hintContent: 'C апреля по ноябрь ежедневно с 9.00 до 18.00',
                                    balloonContent: 'ВитаПлант'
                                });

                                myMap.geoObjects.add(myPlacemark);

                            }

                            </script>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/detail.html
{% extends 'store/main.html' %}
{% load static %}
{% block title %}{{product.name}}{% endblock %}
{% block content %}
<div id="content">
    <div class="inner clearfix">
        <div id="sidebar">
            <ul id="menu" class="left sm sm-theme sm-vertical">
                {% for section in menu %}
                {% if section.name == product.category.name %}
                <li class="selected"> <a href="../{{section.url}}">{{section.name}}</a> </li>
                {% else %}
                <li> <a href="../{{section.url}}">{{section.name}}</a> </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div id="workarea" class="partial clearfix">
            <div id="breadcrumbs" class="default"> <span>
                    <a href="{% url 'store:store' %}" title="Главная">Главная</a>
                </span> <span>>
                    <a href="{% url 'store:products' %}" title="Каталог товаров">Каталог товаров</a>
                </span> <span>> {{product.category.name}}</span> </div>
            <h1 class="title">{{product.name}}</h1>
            <div id="catalog" class="default">
                <div id="catalog-element" class="default">
                    <div class="card clearfix">
                        <div class="col-left">
                            <div class="swiper-container pictures">
                                <div class="swiper-wrapper">
                                    <div class="swiper-slide">
                                        <a class="fancybox" href="{{product.imageURL}}" rel="group-502"> <img src="{{product.imageURL}}" alt="{{product.name}}" title="{{product.name}}" style="width: 420px; height: 315px;"> </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-right">
                            <div class="info">
                                {% if product.is_availible == True %}
                                <div class="marks"> <span class="status" style="font-size: 150%; padding: 2px 8px; border-left: 5px solid; border-color: #3cc051; margin-bottom: 10px;">В наличии</span> </div>
                                {% else %}
                                <div class="marks"> <span class="status" style="font-size: 150%; padding: 2px 8px; border-left: 5px solid; border-color: #ff4d00; margin-bottom: 10px;">Нет в наличии</span> </div>
                                {% endif %}
                                <div class="price">
                                    <div class="actual" style="margin-top: 15px;"> <span class="value" style="font-size: 185%; font-weight: 500;">{{product.price}}</span> <span class="currency" style="font-size: 185%; font-weight: 500;">руб.</span> </div>
                                </div>
                                <div class="detail-text clearfix">
                                    <h2>Описание</h2>{{product.description}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="detail-text clearfix">
                        <h2>Контакты</h2><strong>{{product.contact}}</strong>
                    </div>
                    <br>
                    <div class="back-link"> <a href="../"><img src="{% static 'include/back.png' %}" style="width: 32px; height: 32px; margin-right: 5px;">Назад в раздел</a> </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/footer.html
{% load static %}


<div id="footer">
    <div class="inner clearfix">
        <p><b>Для уточнения цены на товар и наличия товара обратитесь к менеджеру</b></p>
        <div class="left"> Питомник растений Вита Плант
            <br>Все права защищены. </div>
        <div class="center"> г. Саратов, Вольский тракт, 4б
            <br> <i class="fa fa-map-marker"></i> <a href="{% url 'store:contacts' %}">карта проезда</a> </div>
        <script>
        function ScrollUp() {
            var t, s;
            s = document.body.scrollTop || window.pageYOffset;
            t = setInterval(function() { if (s > 0) window.scroll(0, s -= 5);
                else clearInterval(t) }, 5);
        }
        </script>
        <a href="#top" onclick="ScrollUp();return!1;" style="display:block;position:fixed;
            bottom:30px;right:30px;
            opacity:0.7;
            background:#ddd;
            -webkit-border-radius:15px;
            -moz-border-radius:15px;
            border-radius:100px;"><img src="{% static 'include/up.png' %}" style="width: 64px; height: 64px;"></a>
    </div>
</div>

store/templates/store/gallery.html
{% extends 'store/main.html' %}
{% load static %}
{% block title %}Галерея{% endblock %}
{% block content %}
<div id="content">
    <div class="inner clearfix">
        <div id="workarea" class="full clearfix">
            <div id="breadcrumbs" class="default"> <span>
                    <a href="{% url 'store:store' %}" title="Главная">Главная</a>
                </span> <span>>
                    Галерея </span> </div>
            <h1 class="title">Галерея</h1>
            <div class="clearfix">
                {% for image in gallery %}
                <div class="element clearfix" style="width: 25%; display: block; box-sizing: border-box; float: left; width: 500px; height: 500px; marin: 20px; margin-right: 50px; margin-bottom: 50px;">
                    <div style="line-height: 1.2; position: relative; height: 98.75%; margin: 2px; padding: 20px; transition: box-shadow .15s ease-in-out; width: 500px; height: 500px; box-shadow: 0 1px 3px rgba(0,0,0,.15);">
                        <div class="picture">
                            <img src="../static{{image.imageURL}}" style="width: 500px; height: 500px;" />
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <br>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/header.html
{% load static %}

<div id="header">
    <div class="bonnet">
        <div class="inner clearfix">
            <div class="left">
                <div class="vertical-element" style="margin-top: -8%; position: inherit;">
                    <a href="{% url 'store:store' %}"><img style="background: currentColor;" src="{% static 'include/logo.png' %}" width="500" height="200"></a>
                </div>
                <div class="vertical-helper"></div>
            </div>
            <div class="right">
                <div class="vertical-element">
                    <p style="text-align: right;"> <span style="font-size: 16pt;">(8452) 40-01-51 <br>8-903-384-49-84</span>
                </div>
                <div class="vertical-helper"></div>
            </div>
        </div>
    </div>
    <div class="navigation">
        <div class="inner clearfix">
            <input id="menu-state" type="checkbox" />
            <label class="menu-btn" for="menu-state"> <span class="menu-btn-icon"></span> </label>
            <ul id="menu" class="top sm sm-theme sm-flex" style="visibility: hidden;">
                <li> <a href="{% url 'store:products' %}">Каталог</a></li>
                <li> <a href="{% url 'store:price' %}">Прайс-лист</a> </li>
                <li> <a href="{% url 'store:gallery' %}">Галерея</a></li>
                <li> <a href="{% url 'store:services' %}">Услуги</a></li>
                <li> <a href="{% url 'store:contacts' %}">Контакты</a> </li>
            </ul>
        </div>
    </div>
    <div class="clearfix"></div>
</div>

store/templates/store/price.html
{% extends 'store/main.html' %}
{% load static %}
{% block title %}Прайс-лист{% endblock %}
{% block content %}
<div id="content">
    <div class="inner clearfix">
        <div id="workarea" class="full clearfix">
            <div id="breadcrumbs" class="default"> <span>
                    <a href="{% url 'store:store' %}" title="Главная">Главная</a>
                </span> <span>> Прайс-лист</span> </div>
            <h1 class="title">Прайс-лист</h1>
            <table>
                <thead>
                    <tr>
                        <th> Наименование </th>
                        <th> Цена(ед.) </th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in price %}
                    <tr>
                        <td> {{obj.name}} </td>
                        <td> {{obj.price}}р. </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/product_category.html
{% extends 'store/main.html' %}
{% load static %}
{% block title %}{{category}}{% endblock %}
{% block content %}
<div id="content">
    <div class="inner clearfix">
        <div id="sidebar">
            <ul id="menu" class="left sm sm-theme sm-vertical">
                {% for section in menu %}
                {% if section.name == category %}
                <li class="selected"> <a href="../{{section.url}}">{{section.name}}</a> </li>
                {% else %}
                <li> <a href="../{{section.url}}">{{section.name}}</a> </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div id="workarea" class="partial clearfix">
            <div id="breadcrumbs" class="default"> <span>
                    <a href="{% url 'store:store' %}" title="Главная">Главная</a>
                </span> <span>>
                    <a href="{% url 'store:products' %}" title="Каталог товаров">Каталог товаров</a>
                </span> <span>> {{category}}</span> </div>
            <h1 class="title">{{category}}</h1>
            <div id="catalog" class="default">
                <div id="catalog-section-list" class="subsections"> </div>
                <div class="options clearfix">
                    <div class="items-count">
                        <label>Товаров:</label> <strong>{{count}}</strong> </div>
                    <div id="catalog-section" class="table">
                        <div class="elements clearfix">
                            {% for obj in object_list %}
                            <div class="element clearfix" style="width: 25%; display: block; box-sizing: border-box; float: left; width: 200px; height: 350px;">
                                <div style="line-height: 1.2; position: relative; height: 98.75%; margin: 2px; padding: 20px; transition: box-shadow .15s ease-in-out; width: 200px; height: 350px; box-shadow: 0 1px 3px rgba(0,0,0,.15);">
                                    <div class="picture">
                                        <a href="{% url 'store:detail' obj.id %}"> <img src="../static{{obj.imageURL}}" style="width: 165px; height: 125px;" /> </a>
                                    </div>
                                    <div class="title" style="font: 15px/20px 'Roboto', sans-serif;"> <a href="{% url 'store:detail' obj.id %}" style="font-weight: 500;">{{obj.name}}</a> </div>
                                    <br>
                                    {% if obj.is_availible %}
                                    <div class="status"> <span style="background-color: #3cc051; font-size: 80%; padding: 4px 8px; color: #fff;">В наличии</span> </div>
                                    {% else %}
                                    <div class="status"> <span style="background-color: #ff4d00; font-size: 80%; padding: 4px 8px; color: #fff;">Нет в наличии</span> </div>
                                    {% endif %}
                                    <div class="price" style="margin-top: 15px;">
                                        <div class="actual"> <span class="value" style="font: 15px/20px 'Roboto', sans-serif; font-weight: 500; font-size: 130%;">{{obj.price}}</span> <span class="currency" style="font: 15px/20px 'Roboto', sans-serif; font-weight: 500; font-size: 130%;">руб.</span> </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/products.html
{% extends 'store/main.html' %}
{% load static %}
{% block title %}Каталог товаров{% endblock %}
{% block content %}
<div id="content">
    <div class="inner clearfix">
        <div id="sidebar">
            <ul id="menu" class="left sm sm-theme sm-vertical">
                {% for section in menu %}
                <li> <a href="../{{section.url}}">{{section.name}}</a> </li>
                {% endfor %}
            </ul>
        </div>
        <div id="workarea" class="partial clearfix">
            <div id="breadcrumbs" class="default"> <span>
                    <a href="{% url 'store:store' %}" title="Главная">Главная</a>
                </span> <span>
                    > Каталог товаров </span> </div>
            <h1 class="title">Каталог товаров</h1>
            <div id="catalog" class="default">
                <div id="catalog-section-list" class="default">
                    <div class="elements clearfix">
                        {% for section in menu %}
                        <div class="element clearfix">
                            <div class="picture" style="float: left;">
                                <a href="../{{section.url}}"> <img src="{{section.imageURL}}" width="200" height="150" /> </a>
                            </div>
                            <div class="overflow" style="float: left;">
                                <div class="title" style="float: left;">&nbsp;&nbsp;&nbsp;&nbsp;<a href="../{{section.url}}">{{section.name}}</a> </div>
                                <div class="description">&nbsp;&nbsp;&nbsp;&nbsp;{{section.description}}</div>
                            </div>
                        </div>
                        <hr>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/sdetail.html
{% extends 'store/main.html' %}
{% load static %}
{% block title %}{{product.name}}{% endblock %}
{% block content %}
<div id="content">
    <div class="inner clearfix">
        <div id="sidebar">
            <ul id="menu" class="left sm sm-theme sm-vertical">
                {% for section in menu %}
                {% if section.name == product.category.name %}
                <li class="selected"> <a href="../{{section.url}}">{{section.name}}</a> </li>
                {% else %}
                <li> <a href="../{{section.url}}">{{section.name}}</a> </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div id="workarea" class="partial clearfix">
            <div id="breadcrumbs" class="default"> <span>
                    <a href="{% url 'store:store' %}" title="Главная">Главная</a>
                </span> <span>>
                    <a href="{% url 'store:services' %}" title="Каталог товаров">Каталог услуг</a>
                </span> <span>> {{product.category.name}}</span> </div>
            <h1 class="title">{{product.name}}</h1>
            <div id="catalog" class="default">
                <div id="catalog-element" class="default">
                    <div class="card clearfix">
                        <div class="col-left">
                            <div class="swiper-container pictures">
                                <div class="swiper-wrapper">
                                    <div class="swiper-slide">
                                        <a class="fancybox" href="{{product.imageURL}}" rel="group-502"> <img src="{{product.imageURL}}" alt="{{product.name}}" title="{{product.name}}" style="width: 420px; height: 315px;"> </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-right">
                            <div class="info">
                                <div class="price">
                                    <div class="actual" style="margin-top: 15px;"> <span class="value" style="font-size: 185%; font-weight: 500;">{{product.price}}</span> <span class="currency" style="font-size: 185%; font-weight: 500;">руб.</span> </div>
                                </div>
                                <div class="detail-text clearfix">
                                    <h2>Описание</h2>{{product.description}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="detail-text clearfix">
                        <h2>Контакты</h2><strong>{{product.contact}}</strong>
                    </div>
                    <br>
                    <div class="back-link"> <a href="../"><img src="../static/include/back.png" style="width: 32px; height: 32px; margin-right: 5px;">Назад в раздел</a> </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/sproduct_category.html
{% extends 'store/main.html' %}
{% load static %}
{% block title %}{{category}}{% endblock %}
{% block content %}
<div id="content">
    <div class="inner clearfix">
        <div id="sidebar">
            <ul id="menu" class="left sm sm-theme sm-vertical">
                {% for section in menu %}
                {% if section.name == category %}
                <li class="selected"> <a href="../{{section.url}}">{{section.name}}</a> </li>
                {% else %}
                <li> <a href="../{{section.url}}">{{section.name}}</a> </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div id="workarea" class="partial clearfix">
            <div id="breadcrumbs" class="default"> <span>
                    <a href="{% url 'store:store' %}" title="Главная">Главная</a>
                </span> <span>>
                    <a href="{% url 'store:products' %}" title="Каталог товаров"> Каталог услуг</a>
                </span> <span>> {{category}}</span> </div>
            <h1 class="title">{{category}}</h1>
            <div id="catalog" class="default">
                <div id="catalog-section-list" class="subsections"> </div>
                <div class="options clearfix">
                    <div class="items-count">
                        <label>Товаров:</label> <strong>{{count}}</strong> </div>
                    <div id="catalog-section" class="table">
                        <div class="elements clearfix">
                            {% for obj in object_list %}
                            <div class="element clearfix" style="width: 25%; display: block; box-sizing: border-box; float: left; width: 200px; height: 350px;">
                                <div style="line-height: 1.2; position: relative; height: 98.75%; margin: 2px; padding: 20px; transition: box-shadow .15s ease-in-out; width: 200px; height: 350px; box-shadow: 0 1px 3px rgba(0,0,0,.15);">
                                    <div class="picture">
                                        <a href="{% url 'store:sdetail' obj.id %}"> <img src="../../static{{obj.imageURL}}" style="width: 165px; height: 125px;" /> </a>
                                    </div>
                                    <div class="title" style="font: 15px/20px 'Roboto', sans-serif;"> <a href="{% url 'store:sdetail' obj.id %}" style="font-weight: 500;">{{obj.name}}</a> </div>
                                    <div class="preview-text">
                                        <p style="font: 15px/20px 'Roboto', sans-serif; word-break: break-all;">{{obj.description}}</p>
                                    </div>
                                    <div class="price" style="margin-top: 15px;">
                                        <div class="actual"> <span class="value" style="font: 15px/20px 'Roboto', sans-serif; font-weight: 500; font-size: 130%;">{{obj.price}}</span> <span class="currency" style="font: 15px/20px 'Roboto', sans-serif; font-weight: 500; font-size: 130%;">руб.</span> </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
<div id="content">
    <div class="inner clearfix">
        <div id="workarea" class="full clearfix">
            <h3>Каталог товаров</h3>
            <div id="catalog-section-list" class="panel">
                <div class="elements clearfix">
                    {% for section in menu %}
                    <div class="element clearfix">
                        <a href="{{section.url}}">
                            <div class="picture" style="background-image: url('{{section.imageURL}}');"></div>
                            <div class="title"> <span>{{section.name}}</span> </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
                <hr>
                <br>
            </div>
        </div>
    </div>
</div>
{% endblock %}